   name: build
   on: [push, workflow_dispatch]
   jobs:
     win:
       runs-on: windows-latest
       steps:
         - uses: actions/checkout@v4
         - run: cmake -B build -A x64
         - run: cmake --build build --config Release
         - uses: actions/upload-artifact@v4
           with:
             name: BedrockClient
             path: |
               build/Release/BedrockClient.dll
               build/Release/injector.exe
